export const en = {
  panel: 'Monitor Pro', intro: 'Live resources on the Harness host', live: 'Live', starting: 'Starting', degraded: 'Partial readings', error: 'Collection failed', stopped: 'Stopped', stale: 'Readings are stale', loading: 'Waiting for the first sample…', retry: 'Retry', pause: 'Pause view', resume: 'Resume view', paused: 'View paused', settings: 'Display settings', close: 'Close', cpu: 'CPU', memory: 'Memory', network: 'Network', diskIO: 'Disk I/O', diskSpace: 'Disk capacity', battery: 'Battery', cpuSpeed: 'CPU frequency', cpuTemp: 'CPU temperature', gpu: 'GPU', power: 'Power', socPower: 'SoC power', batteryPower: 'Battery net power', unavailable: 'Unavailable on this source or device', disabled: 'No metrics enabled', download: 'Download', upload: 'Upload', read: 'Read', write: 'Write', active: 'Active', used: 'Used', available: 'Available', swap: 'Swap', total: 'Total', cores: 'Per-core CPU', core: 'Core', health: 'Health', charging: 'Charging', discharging: 'On battery', plugged: 'Plugged in', remaining: 'Estimated remaining', minutes: 'min', source: 'Source', uptime: 'Uptime', interval: 'Sampling interval', history: 'History', samples: 'samples', unit: 'Units', binary: 'Binary (KiB)', decimal: 'Decimal (kB)', decimals: 'Decimal places', visible: 'Visible cards', order: 'Card order', up: 'Move up', down: 'Move down', export: 'Export JSON', host: 'Host', configuration: 'Edit collector options in Plugins → Monitor Pro → configuration.', networkNote: 'SI sums active non-loopback interfaces; VPNs and bridges can overlap.', goNote: 'Go reports the first eligible network interface and disk. GPU and per-core CPU are unavailable.', mactopNote: 'mactop reports SoC temperature/power and treats active memory as used. Shared GPU memory is unavailable.', seconds: 's', reset: 'Reset display', time: 'Last sample', vram: 'GPU memory', networkUnit: 'Network rates', bytes: 'Bytes/s', bits: 'Bits/s',
};
export type TextKey = keyof typeof en;
export const zh: Record<TextKey, string> = {
  panel: 'Monitor Pro', intro: '实时监控 Harness 主机资源', live: '实时', starting: '正在启动', degraded: '部分指标失败', error: '采集失败', stopped: '已停止', stale: '数据已过期', loading: '等待首次采样…', retry: '重试', pause: '暂停显示', resume: '恢复显示', paused: '显示已暂停', settings: '显示设置', close: '关闭', cpu: 'CPU', memory: '内存', network: '网络', diskIO: '磁盘读写', diskSpace: '磁盘容量', battery: '电池', cpuSpeed: 'CPU 频率', cpuTemp: 'CPU 温度', gpu: 'GPU', power: '功耗', socPower: 'SoC 总功耗', batteryPower: '电池净功率', unavailable: '当前采集源或设备不提供此指标', disabled: '没有启用监控指标', download: '下载', upload: '上传', read: '读取', write: '写入', active: '活跃', used: '已用', available: '可用', swap: '交换空间', total: '总计', cores: '每核 CPU', core: '核心', health: '健康度', charging: '充电中', discharging: '使用电池', plugged: '已接电', remaining: '预计剩余', minutes: '分钟', source: '采集源', uptime: '运行时间', interval: '采样间隔', history: '历史记录', samples: '个采样', unit: '容量单位', binary: '二进制（KiB）', decimal: '十进制（kB）', decimals: '小数位数', visible: '显示卡片', order: '卡片顺序', up: '上移', down: '下移', export: '导出 JSON', host: '主机', configuration: '在「插件 → Monitor Pro → 配置」中修改采集选项。', networkNote: 'SI 汇总活动的非回环接口；VPN 和网桥可能重复统计。', goNote: 'Go 使用首个符合条件的网卡和磁盘，不提供 GPU 和每核 CPU 数据。', mactopNote: 'mactop 提供 SoC 温度和总功耗，活跃内存等同已用内存，不提供 GPU 共享显存。', seconds: '秒', reset: '重置显示', time: '最近采样', vram: '显存', networkUnit: '网络速率单位', bytes: '字节/秒', bits: '比特/秒',
};
export const zhTw: Record<TextKey, string> = {
  panel: 'Monitor Pro', intro: '即時監控 Harness 主機資源', live: '即時', starting: '正在啟動', degraded: '部分指標失敗', error: '採集失敗', stopped: '已停止', stale: '資料已過期', loading: '等待首次採樣…', retry: '重試', pause: '暫停顯示', resume: '恢復顯示', paused: '顯示已暫停', settings: '顯示設定', close: '關閉', cpu: 'CPU', memory: '記憶體', network: '網路', diskIO: '磁碟讀寫', diskSpace: '磁碟容量', battery: '電池', cpuSpeed: 'CPU 頻率', cpuTemp: 'CPU 溫度', gpu: 'GPU', power: '功耗', socPower: 'SoC 總功耗', batteryPower: '電池淨功率', unavailable: '目前採集來源或裝置不提供此指標', disabled: '沒有啟用監控指標', download: '下載', upload: '上傳', read: '讀取', write: '寫入', active: '活躍', used: '已用', available: '可用', swap: '交換空間', total: '總計', cores: '每核心 CPU', core: '核心', health: '健康度', charging: '充電中', discharging: '使用電池', plugged: '已接電', remaining: '預計剩餘', minutes: '分鐘', source: '採集來源', uptime: '運作時間', interval: '採樣間隔', history: '歷史記錄', samples: '個採樣', unit: '容量單位', binary: '二進位（KiB）', decimal: '十進位（kB）', decimals: '小數位數', visible: '顯示卡片', order: '卡片順序', up: '上移', down: '下移', export: '匯出 JSON', host: '主機', configuration: '在「外掛 → Monitor Pro → 設定」中修改採集選項。', networkNote: 'SI 彙總活動的非回環介面；VPN 和網路橋接可能重複統計。', goNote: 'Go 使用首個符合條件的網卡和磁碟，不提供 GPU 和每核心 CPU 資料。', mactopNote: 'mactop 提供 SoC 溫度和總功耗，活躍記憶體等同已用記憶體，不提供 GPU 共用顯存。', seconds: '秒', reset: '重設顯示', time: '最近採樣', vram: '顯存', networkUnit: '網路速率單位', bytes: '位元組/秒', bits: '位元/秒',
};
export const ja: Record<TextKey, string> = {
  panel: 'Monitor Pro', intro: 'Harness ホストのリソースをリアルタイムで監視', live: 'リアルタイム', starting: '起動中', degraded: '一部の取得に失敗', error: '取得に失敗', stopped: '停止', stale: 'データが古くなっています', loading: '最初のサンプルを待っています…', retry: '再試行', pause: '表示を一時停止', resume: '表示を再開', paused: '表示を一時停止中', settings: '表示設定', close: '閉じる', cpu: 'CPU', memory: 'メモリ', network: 'ネットワーク', diskIO: 'ディスク I/O', diskSpace: 'ディスク容量', battery: 'バッテリー', cpuSpeed: 'CPU 周波数', cpuTemp: 'CPU 温度', gpu: 'GPU', power: '電力', socPower: 'SoC 消費電力', batteryPower: 'バッテリー正味電力', unavailable: 'この取得元またはデバイスでは利用できません', disabled: '有効な監視項目がありません', download: '受信', upload: '送信', read: '読み取り', write: '書き込み', active: 'アクティブ', used: '使用中', available: '利用可能', swap: 'スワップ', total: '合計', cores: 'CPU コア別', core: 'コア', health: '状態', charging: '充電中', discharging: 'バッテリー使用中', plugged: '電源接続中', remaining: '推定残り時間', minutes: '分', source: '取得元', uptime: '稼働時間', interval: '取得間隔', history: '履歴', samples: 'サンプル', unit: '容量の単位', binary: '2 進数（KiB）', decimal: '10 進数（kB）', decimals: '小数桁数', visible: '表示するカード', order: 'カードの順序', up: '上へ', down: '下へ', export: 'JSON を保存', host: 'ホスト', configuration: 'プラグイン → Monitor Pro → 設定で取得オプションを変更できます。', networkNote: 'SI はアクティブな非ループバックインターフェースを合計します。VPN やブリッジは重複する場合があります。', goNote: 'Go は最初の対象ネットワークとディスクを使用します。GPU とコア別 CPU は利用できません。', mactopNote: 'mactop は SoC 温度と消費電力を返します。アクティブメモリは使用中メモリと同じです。共有 GPU メモリは利用できません。', seconds: '秒', reset: '表示をリセット', time: '最終サンプル', vram: 'GPU メモリ', networkUnit: 'ネットワーク速度単位', bytes: 'バイト/秒', bits: 'ビット/秒',
};
